-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgSN9JYwhWCDtmLR5T
wVStYVoawU9MTodH74jEPxNsFQigCgYIKoZIzj0DAQehRANCAARnjyETeCArnQ4l
FarjiKDKuimw4wfb1+5gWavcm8dQ3/yydW5His1ibHC+kz9koYK0GrYUm4NVPFC1
njtTPEyI
-----END PRIVATE KEY-----